README.md
Simplifies the `package.json` reference in the docs.
- The reader already understands that `package.json` has other fields.
- It's not necessarily true that there are more fields below the property `scripts`.
=> docs: Remove extra ellipses from package.json examples

README.md
Adds an npm link and badge to the README
Preview:
=> docs: Add an npm link and badge to README

converter/Dockerfile, converter/convert, converter/generate-package-lock, converter/with-package-without-framework/package-lock.json, converter/with-package-without-framework/package.json, converter/without-package/package-lock.json, converter/without-package/package.json
This replaces the local dependency on @google-cloud/functions-framework with the dependency on the module published to npm.
=> Update function-to-app converter to depend on the module published to npm

README.md, src/index.ts, src/invoker.ts, test/invoker.ts
Fixes #4.
- Removes redundant `function` from CLI/env vars for `target` and `signature-type`
- Updates docs
- Moves string literals into constants to reduce renaming multiple pieces of code and clearly define the library interface in 1 place.
=> fix #4: Removes 'function' prefix from CLI args

README.md, docs/README.md
Empty for now.
See https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/40#issuecomment-502903362.
=> Create docs/ README.md

src/index.ts
Adds a CLI help flag (-h, --help). Fixes #31.
```sh
granttimmerman @ ~/Documents/trash/testff
❤ functions-framework --help
Usage:
functions-framework --target=helloWorld --port=8080
Documentation:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs
```
CC: @grayside
=> fix: Adds CLI help flag. Fixes #31

docs/README.md
Simple change - added a new item to the TODO list with reference to Local Debug thread. That should help in preparing complete documentation later on.
=> Add todo/reference to Local Debug thread

converter/Dockerfile, converter/convert, converter/install-function-dependencies, converter/with-package-with-framework/package.json, converter/with-package-without-framework/package.json
Function dependencies are now installed using yarn when yarn.lock is
present in the application source code.
=> Add support for installing dependencies through yarn

docs/README.md
Adds steps to attach a debugger to your function running locally.
Addresses:
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/47
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/15
=> Add instructions for local debugging

converter/convert
The install script should be copied when there is a package.json with or
without the framework dependency, not when there is not package.json.
=> Fix convert to copy the dependency install script in the correct cases

README.md, src/index.ts
Hey,
In my use of Cloud Functions, i've encountered with the situation of using different folders to hold my functions, so this will be helpful for me and any others.
=> Add a source flag/env option to add flexibility to execution path

.gitignore, docs/README.md, docs/docker.md
Modifies PR to add instructions on how to deploy the FF to Cloud Run:
See https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/28
R: @grayside
=> Docs: Add Docker Tutorial Doc

src/invoker.ts
During our cloud function deployment we encountered error:
```
Deployment failure:
Function failed on loading user code. Error message: /srv/functions/node_modules/@google-cloud/functions-framework/build/src/invoker.js:89
if (ex.stack.includes('Cannot find module')) {
^
TypeError: Cannot read property 'includes' of undefined
at Object.getUserFunction (/srv/functions/node_modules/@google-cloud/functions-framework/build/src/invoker.js:89:22)
at Object.<anonymous> (/srv/functions/node_modules/@google-cloud/functions-framework/build/src/index.js:67:33)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12) …
```
=> Adding null check in catch block

docs/README.md
Fixes #37, and pick ups on #40.
=> New section documentation on how to perform local PubSub testing

README.md, src/index.ts
This was the default before introducing the --source flag. Making root ('/') the default breaks existing projects if users don't specify --source.
=> Change the default function directory to the current working directory instead of root

src/index.ts, src/invoker.ts, test/invoker.ts
- Specifies _exact_ function target instead of `*`.
- Fixes #33.
- Ran linter.
=> fixes #33: Only listen to functionTarget.

src/index.ts
I removed `'/'` from `CODE_LOCATION` that set the default function directory to root in commit #77. This causes this error in 1.3.0,
```
npx @google-cloud/functions-framework --target=helloWorld
The "path" argument must be of type string. Received type undefined
```
When `--source` flag and `FUNCTION_SOURCE` env var are not specified, one of the 'path' arguments in `resolve()` is undefined. This causes the error above.
I've added empty string as an argument in the case above.
fixes issue #89
=> fix: use empty string path when function source is not specified

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.3.1

docs/README.md
To be able to parse the event properly, content type must be set. This is at least true for my environment.
=> Changed curl command to include json content-type

README.md
Adds a useful video explaining the Functions Framework to the repo's README.
Fixes #73.
=> docs: add video about FF

docs/README.md
So far, Just only convert from full-width double quotation (`”`) to single-width double quotation (`"`) .
=> Fix double quotation from full-width character

docs/events.md
Fixes user submitted documentation about using the Pub/Sub emulator.
Tested locally.
Fixes #85
R: @grayside
=> docs: update pub sub docs with instructions that work

src/index.ts
With this option, we can load a function without starting a server, i.e.
```
functions-framework --target=helloWorld --dry-run=true
```
so that it can be used in builds to check for syntax errors, etc.
=> feat: add --dry-run option to load user's function but not start a server

src/invoker.ts
Currently, when running the Functions Framework in a Docker container by running `docker run`, one cannot stop the running container with Ctrl+C. This is because the Functions Framework doesn't handle SIGINT in the ErrorHandler. This change handles SIGINT in the similar fashion as SIGTERM i.e. close the web server and exit the process.
=> fix: handle SIGINT in ErrorHandler

package-lock.json, src/cloudevents.ts, src/invoker.ts, src/logger.ts, src/types.ts
This PR begins to refactor the monolithic files into separate files.
Has no functional changes.
Part of https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/134.
=> refactor: split files

src/cloudevents.ts, src/invoker.ts
- Moves `getBinaryCloudEventContext` into `src/cloudevents.ts`
- Inlines global `rawBodySaver` method (not really needed outside `getServer`
- Cleans up a few comments
=> refactor: extract cloudevents functions, privateize file-global identifiers

docs/events.md
Use the proper function name for the example.
=> Fix PubSub Event Example

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.6.0

renovate.json
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/168
I'm not sure exactly how to make PRs only bump versions if minor or major (rather than patch), but this should help a bit.
=> chore: make renovate not update as often

src/invoker.ts, src/logger.ts
Doesn't log assuming an error on process.exit. Keeps same functionality.
Tested locally.
```
npx @google-cloud/functions-framework --target=helloWorld
Serving function...
Function: helloWorld
URL: http://localhost:8080/
^CReceived SIGINT
```
Not sure about upstream impact.
=> fix: do not send error when error code is fine

package-lock.json, src/invoker.ts, test/invoker.ts
Other changes:
* Send an empty response body for the same with the 404, since   these URLs are not intended for human consumption.
* Add an invocation count assertion to the test to confirm that   these URLs do not in fact result in the function call.
* Accept npm's lockfile update of this own package version.
* Nit: wrap long comments at 80 characters.
Fixes: #191
=> Don't call the function after a 404 on /{robots.txt,favicon.ico}

README.md
Documents what `req` and `res` mean. Got this feedback from Sheets Platinum team.
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/199
=> docs: mention express as the request/response parameters

README.md
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/211.
- Formats document to have 1 H1 for the title and subheaders be H2s.
- Collects quickstarts in one header
- Adds quickstart for using buildpacks
- Some minor formatting so the README renders nicely.
=> docs: add buildpacks/docker quickstart

src/index.ts, src/invoker.ts, src/router.ts, src/server.ts, src/types.ts, test/invoker.ts
Refactors the router/server/invoker.
The invoker file is pretty large, tries to slim down that file by creating a new `router.ts` file.
Does not change functionality.
---
Hoping to integrate the CE SDK next. We probably should add some more tests.
=> refactor: split invoker and router

.github/workflows/conformance.yml, .github/workflows/lint.yml, .github/workflows/unit.yml
This CI PR slightly changes the config to not run on every push.
- Run CI whenever:
- Pushing to master
- Pull requests
(Sorry for the extra PR)
=> ci: don't run when pushing to non-master branches

src/server.ts
Disables Express' x-powered-by header. This is a recommendation from Express
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/206
=> feat: disable x-powered-by header

src/invoker.ts
Fixes CloudEvent signature with callbacks.
`(cloudevent, callback) =>`
=> fix: fix cloudevent signature callbacks

src/logger.ts
Fixes #239.
res.send when receiving a sole numeric argument will set thee statuc code to that number.
This breaks HTTP communication as some numbers are not valid HTTP response codes.
For example, in the original issue the code is being set to 2. Which probably comes from the UNKNOWN error response of an RPC call.
This makes that the function is reported as having a `connection error`.
=> fix: Do not pass numeric arguments to res.send

src/invoker.ts
Simplifies CTRL + C exit by immediately exiting process. Should make the local development exiting process better. Removes the "Received ^C" message. Tested locally.
Fixes: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/260
More context is here too: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/126#issuecomment-638220477
I believe the Node server was kept alive in some cases, even after a SIGINT, which makes the local dev process frustrating.
```
npm start
> ffnodelocalerr@1.0.0 start /Users/timmerman/Documents/trash/ffnodelocalerr
> functions-framework --target=helloWorld
Serving function...
Function: helloWorld
Signature type: http
URL: http://localhost:8080/
^C%      
```
```json
{
"name": "ffnodelocalerr",
"version": "1.0.0", …
```
=> fix: smooth functions crash

.github/workflows/conformance.yml, src/invoker.ts, src/middelware/ce_to_legacy_event.ts, src/middelware/index.ts, src/server.ts, test/integration/legacy_event.ts, test/middleware/ce_to_legacy_event.ts
This commit adds middleware that converts known GCP CloudEvent requests to the equivalent legacy context/data event schema. This enables functions using the `EVENT` signature type to consume events from a source the publishes CloudEvents.
=> Implement CloudEvent to legacy event conversion

.github/workflows/conformance.yml, src/cloudevents.ts, src/functions.ts, src/middelware/ce_to_legacy_event.ts, src/middelware/legacy_event_to_cloudevent.ts, src/server.ts, test/integration/cloudevent.ts, test/middleware/ce_to_legacy_event.ts, test/middleware/legacy_event_to_cloudevent.ts
This commit adds express middleware to convert legacy GCF requests to the equivalent CloudEvent requests. This enables developers to leverage cloud events in functions that consume events from GCP products that don't yet produce CloudEvents.
=> Convert legacy GCF events to CloudEvents

.github/workflows/conformance.yml, package-lock.json, src/cloudevents.ts, src/functions.ts, src/invoker.ts, src/middleware/background_event_to_cloudevent.ts, src/middleware/cloudevent_to_background_event.ts, src/pubsub_middleware.ts, src/server.ts, test/integration/cloudevent.ts, test/integration/legacy_event.ts, test/middleware/background_event_to_cloudevent.ts, test/middleware/cloudevent_to_background_event.ts, test/pubsub_middleware.ts
This commit re-enables the logic to automatically convert between legacy
and cloudevent request payloads to match the configured signature type.
This was reverted in #289. Now that we have a plan for how it will
work, we should re-enable it.
This reverts commit d894b490dda7c5fd4690cac884fd9e41a08b6668.
=> feat: Enable cloudevent conversion logic

src/index.ts, src/router.ts, src/server.ts, src/types.ts, test/integration/cloudevent.ts, test/integration/http.ts, test/integration/legacy_event.ts
This commit refactors the SignatureType enum into an array of strings declared [as const](https://github.com/Microsoft/TypeScript/pull/29510). This allows the `SignatureType` type to be expressed as a union type, which works a bit better when parsing a user provided string.
This is some simple refactoring in preparation for declarative function signatures.
BREAKING CHANGE: exported SignatureType type is converted from an enum to a union type
=> refactor!: use a union type for SignatureType

src/index.ts, src/options.ts, test/options.ts
This commit refactors the logic for parsing CLI flags and env vars into a separate module and adds unit tests.
=> refactor: options parsing

package.json, src/index.ts, src/main.ts
This commit moves the call to bootstrap the express server out of
index.ts. This is an important change now that we have declarative
function signatures because we expect developers to include an import
statement for the functions-framework. Before this change doing so would
have automatically started the express http server which makes it hard
to do things like write unit tests.
Fixes #350
=> refactor: move the bin entrypoint out of index.ts

experimental/generate_cloudevents/src/generate.ts, experimental/generate_cloudevents/src/utils.ts, src/cloudevent_types/CloudEvent.ts, src/cloudevent_types/GoogleCloudEvent.ts, src/cloudevent_types/cloud/audit/v1/LogEntryData.ts, src/cloudevent_types/cloud/cloudbuild/v1/BuildEventData.ts, src/cloudevent_types/cloud/firestore/v1/DocumentEventData.ts, src/cloudevent_types/cloud/pubsub/v1/MessagePublishedData.ts, src/cloudevent_types/cloud/scheduler/v1/SchedulerJobData.ts, src/cloudevent_types/cloud/storage/v1/StorageObjectData.ts, src/cloudevent_types/firebase/analytics/v1/AnalyticsLogData.ts, src/cloudevent_types/firebase/auth/v1/AuthEventData.ts, src/cloudevent_types/firebase/database/v1/ReferenceEventData.ts, src/cloudevent_types/firebase/remoteconfig/v1/RemoteConfigEventData.ts, src/cloudevent_types/firebase/testlab/v1/TestMatrixEventData.ts
This commit adds the output of the experiment/generate_cloudevents pipeline to the nodejs FunctionsFrameworks. This adds type interfaces for all known Google CloudEvent payloads, but it does not make any changes to the FFs to consume them yet. Those changes will be made in a subsequent PR.
All the types added by this PR can be deleted once the npm packages produced by googleapis/google-cloudevents-nodejs is ready for production usage.
=> feat: Add Google CloudEvent Types

docs/generated/api.json, package-lock.json, package.json, test/function_registry.ts, test/function_wrappers.ts, test/loader.ts
This is a dev dependency that seems to be unused. Currently it is
pulling in a transitive dependency that is preventing us from using `npm
ci` in our workflows.
=> chore: remove power assert

src/function_registry.ts, test/function_registry.ts
Adds basic function name validation for registered functions. As almost any sequence of strings can be URL encoded into a valid URL when URL encoded, we check for valid function names using a regex.
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/388
=> ci: add basic validation for declarative function names

docs/README.md, docs/testing-functions.md, package.json, src/testing.ts, test/integration/cloud_event.ts, test/integration/http.ts
This commit adds some helpers for unit testing cloud functions along with some documentation about how to use them. Much of inspiration came from the Ruby Functions Framework: https://github.com/GoogleCloudPlatform/functions-framework-ruby/blob/main/docs/testing-functions.md
A readable preview of the docs is [here](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/f2ce0b97e2e1f188e3e892da07404127b1ecbe20/docs/testing-functions.md).
Eventually we will want to update [this guide on DevSite](https://cloud.google.com/functions/docs/testing/test-overview) to match the guidance in the docs we are adding in this PR; however, at the moment none of our public docs or samples are using the declarative function signature APIs so the helpers / instructions here are not …
=> feat: add testing helpers and instructions

.github/workflows/docs.yml, .github/workflows/publish.yml, docs/generated/api.json, docs/generated/api.md, package-lock.json, package.json, src/cloud_events.ts, src/function_registry.ts, src/function_wrappers.ts, src/functions.ts, test/function_wrappers.ts, test/integration/cloud_event.ts
This commit updates to the latest CESDK which provides a generic interface for CloudEvents. This is an additive, non-breaking change to our registration API:
providing a template type on the registration function:
```typescript
import * as functions from '@google-cloud/functions-framework';
functions.cloudEvent<string>('helloTypes', (ce) => {
// the event data is strongly typed here
ce.data.length;
});
```
providing a template type on the argument annotation:
```typescript
import {CloudEvent}, * as functions from '@google-cloud/functions-framework';
functions.cloudEvent('helloTypes', (ce: CloudEvent<string>) => {
// the event data is strongly typed here
ce.data.length;
});
```
not providing a template is still allowed:
```typescript
import functions from …
```
=> feat!: update to latest version of clouevents sdk

docs/typescript.md
Update typescript readme as proposed in [issue](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/254)
=> docs: add instructions for deploying with typescript codebase

docs/debugging.md
After #377 adopting the entrypoint to ./build/src/main.js, the Node Inspector does not work as expected. 
By pointing on the symlinked executable in node_modules/.bin/functions-framework (which is reflecting the right entry point) someone can use the functions framework in conjunction with the node inspector as expected.
=> fix: patching debugging docs

src/invoker.ts, src/logger.ts, test/conformance/function.js, test/integration/cloud_event.ts, test/integration/http.ts, test/integration/legacy_event.ts
This commit updates the http response we send when the customer's function throws to:
1. always send a 500 HTTP status
2. strip the error message from the response body when running in production
=> fix!: send correct response code on exception

src/server.ts
The Express.js framework handles [eTags] (https://expressjs.com/en/api.html#app.settings.table) by default. Therefore, will respond with HTTP 304 Not Modified when a known eTag header value is present in a request with the same response.
In all other Function Framework runtime implementations, this behavior is not  implemented, and this caching behavior, which can be considered as an implementation detail, could be explicitly addressed by a developer as needed.
This pull request aims make the NodeJs runtime version behaving the same as runtime implementations for GO, Java, Ruby, .Net Core, Python, and PHP.
=> Disable Express eTag response header for consistent FF behaviour across FF runtimes 

src/server.ts
Reverts GoogleCloudPlatform/functions-framework-nodejs#433 due to failed lint check.
=> Revert "Disable Express eTag response header for consistent FF behaviour across FF runtimes "

.github/renovate.json
We don't need to keep having PRs update deps in docs or experimental folders.
=> chore: do not renovate docs/experimental folders

.github/renovate.json
We have a few too many PRs that are minor/patch versions without significant updates.
This PR adds a schema to the renovate config and sets the package rules to group minor/patch PRs.
Automerge true also didn't work as expected - it is removed here.
References:
- https://docs.renovatebot.com/presets-group/#groupallnonmajor
- https://stackoverflow.com/questions/66471226/renovate-combine-all-updates-to-one-branch-pr
See:
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/451
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/449
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/448
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/447
- https://github.com/GoogleCloudPlatform/functions-framework-nodejs/p …
=> chore: update renovate match rules

docs/typescript-pubsub.md
Just something that took me a while to figure out. I think it can be useful to have it here and I couldn't find it documented anywhere. Cheers.
=> docs: added PubSub Typescript doc

.github/workflows/buildpack-integration-test.yml
Newest version of the client does not require a builder-tag and will use "latest" by default.
=> chore: update buildpack test

docs/typescript.md
This was very out of date. Updated to reflect most recent version of the FF.
fixes #472, #469
=> docs: re-write of the typescript user guide

.github/workflows/publish.yml
Per instructions for using the publish service
"We take care in this job to set the registry to the publish service after any npm commands that install dependencies (e.g. npm ci), because the publish service is only meant for publishing. If you try to npm install with the publish service registry, it will fail."
=> chore: fix publish npm package workflow

src/loader.ts, test/loader.ts
The function framework's current behavior is to load an exported function named 'function' if one exists as a fallback if the user's declared target function is not found. This behavior is counter intuitive and can hide misconfiguration from the user.
In this CL a breaking change is made to disable this fallback behavior in favor of failing fast so that the configuration error is highly visible to the user.
=> fix: remove default fallback when target function does not exist

.github/renovate.json
The renovate configs currently in use is not correctly ignoring the docs and experimental folders, and seems to not group non major updates together.
* The previous renovate config ```ignorePaths``` was not working due to a current issue with renovate itself where ```ignorePaths``` is being overwrited by the ```coinfig:base``` defaults. The suggested fix is to use ```globalExtends``` property. Discussion used: https://github.com/renovatebot/renovate/discussions/14793
* Changed config to use the ```group:allNonMajor``` extension which ended up grouping non-major versions correctly.
Tested by forking repo, changing versions manually, and then running a locally cloned renovate bot against my fork with the updated renovate config file.
Example of how non major grouping would look like:
=> fix: make renovatebot's ignorePath and grouping of non-major updates work correctly

src/loader.ts, test/loader.ts
The existing module resolution logic has two logic errors which create a confusing experience when the customer's module isn't found:
1. `null` is never returned even when the module is not found, this means function framework doesn't early return with an exception when it should if the function does not exist.
2. The error message will accurately reflect the original path instead of including `/function.js` prefix which gets incorporated as a side effect of the implementation today.
This change simplifies the function and cleans up these errors.
=> fix: module resolution returns early and accurate error messages on failure

.github/renovate.json
[Typescript 5.1 requires node >= 14.17](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-1.html#breaking-changes). Functions framework needs to support older versions (10, 12) hence the transpiler will stop working for older node runtimes.
=> chore: Ignore typescript dependency updates

src/invoker.ts
Despite the Node.js docs indicating that the [exit code should always be a number](https://nodejs.org/docs/latest-v10.x/api/process.html#process_event_exit) it seems this is unchecked and, in fact, `process.exit` may be called with a string value.
Verified experimentally:
```
// test.js
const process = require("process");
process.on('exit', function(code) {
console.log(typeof code);
console.log(code);
});
process.exit('abc');
// output
string
abc
```
Some Cloud Function users report errors on shutdown when either their code or a dependency calls process.exit with a string value. To account for this the exit code check is updated to use string comparison to account for the possibility of a string exit code.
=> fix: framework fails to shutdown gracefully when exit code is a string

README.md
The current README show the conformance tests are failing.
This PR re-adds the GitHub badges using the links provided by the GitHub web UI, create badge button.
It uniformly adds `actions/worksflows/` in the URLs and references the workflow badge by the workflow file name.
=> docs: fix GitHub Actions badges

docs/generated/api.json, docs/generated/api.md, package-lock.json, package.json, src/function_registry.ts, src/functions.ts, src/main.ts, src/middleware/timeout.ts, src/options.ts, src/server.ts, src/testing.ts, test/integration/legacy_event.ts, test/middleware/timeout.ts, test/options.ts
This commit adds a nodejs AbortController to the HTTP request object that is used to signal cancellation for a function execution in the event of a timeout or client disconnect.
=> feat: AbortController to signal request timeouts

docs/generated/api.json, src/cloud_events.ts, src/function_registry.ts, src/function_wrappers.ts, src/functions.ts, src/invoker.ts, src/loader.ts, src/logger.ts, src/middleware/background_event_to_cloud_event.ts, src/middleware/cloud_event_to_background_event.ts, src/options.ts, src/pubsub_middleware.ts, src/server.ts, src/testing.ts, src/types.ts
Fix a bunch of ts-doc formatting issues that were spewing warnings.
=> chore: udpate ts-doc annotations

.eslintrc.json, src/logger.ts, test/logger.ts
`firebase-functions/logger` writes structured logs to stdout and stderr by default, and makes these pretty with ANSI color codes.
When functions-framework intercepts these messages to assign execution IDs, it handles them incorrectly in two ways.
First, when the log emitted on stdout or stderr is already a structured log, we override (ignore) the severity set by the logger.  This commit avoids changing severity if it's already set.
Second, when parsing the message and attempting to determine if it's already a json object/structured log, it doesn't handle ANSI escape codes (https://en.wikipedia.org/wiki/ANSI_escape_code) used to control color, so parsing these will fail.  This means that severity handling falls back to just looking at whether the message came from stdout or stderr, so …
=> fix: parse structured logs, and handle ANSI escape codes in logs

src/logger.ts, test/logger.ts
For text log, we don't set severity level so that it will fall back to default behavior, i.e. severity: "DEFAULT".
=> fix: Don't set severity level for text log.

src/function_registry.ts, test/integration/cloud_event.ts
This commit adds the typing to specific a CloudEventFunctionWithCallback as the handler for functions.cloudEvent() function.
Fixes #633
=> fix: Fix typings for functions.cloudEvent to include callback.

.github/workflows/publish.yml, .github/workflows/scorecard.yml
the hardener is currently blocking traffic to these endpoints but they are required for the pipeline
=> chore: add missing allowed-endpoints to workflows

.github/workflows/publish.yml, .github/workflows/scorecard.yml
- objects.githubusercontent.com:443 is required for the publish workflow
- api.scorecard.dev:443 is required for the openssf scorecard
=> chore: allowlist more endpoints

src/logger.ts
This should fix the "Error: No default engine was specified and no extension was provided" issues we have been seeing.
fixes #657, #652
=> fix: do not call render in the errorHandler

docs/generated/api.json, docs/generated/api.md.api.md, src/async_local_storage.ts, src/execution_context.ts, src/functions.ts, src/logger.ts, test/async_local_storage.ts, test/execution_context.ts, test/logger.ts
1. fix trace context pattern (#655)
2. remove `logging.googleapis.com/trace` as we don't have project id in functions framework (#656)
3. respect provided `logging.googleapis.com/spanId` fields for structured logs
=> fix: fix trace context pattern, remove trace id and respect logging span id field.

README.md, src/options.ts, src/server.ts, src/testing.ts, test/integration/legacy_event.ts, test/options.ts
Can be set to a single path or regular expression for URL paths that should get an empty 404 response without invoking the user function. Historically we have always filtered out `/robots.txt|/favicon.ico` but have received feedback from customers who would like to overrider this behavior.
=> introduce a new option for configuring ignored routes

.github/workflows/buildpack-integration-test.yml, .github/workflows/conformance.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, .github/workflows/unit.yml
Updates all our Github workflows to drop versions 10, 12, 14, and 16 which are all deprecated. And then start including 22.
=> chore: nodejs versions in github workflows

package-lock.json, package.json
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/673.
/cc @matthewrobertson
=> fix(deps): downgrade @types/express to v4

src/server.ts
Fixes a bug in which we are filtering all routes when `IGNORED_ROUTES=""`.
=> fix: correct handling of IGNORED_ROUTES set to empty
