GoogleCloudPlatform/functions-framework-nodejs

README.md
This is mostly a test commit, although the title could be simplified.
=> docs: Simplify CloudEvents README title

.gitignore
Creates a `.gitignore` file.
Fixes #1.
=> fix: Create gitignore for node_modules and other files

converter/convert
This fixes the issue where some hidden files are not moved.
=> Adding shopt-s dotglob to converter.

src/invoker.ts
=> Log errors after "finished functions"

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.3.0

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.3.2

README.md
Adds a badge the the README showing npm downloads: [![npm downloads](https://img.shields.io/npm/dm/@google-cloud/functions-framework.svg)](https://npmcharts.com/compare/@google-cloud/functions-framework?minimal=true)
=> Add npm downloads badge to README.md

docs/README.md, docs/docker.md
=> docs: Remove beta from gcloud run

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.4.0

src/index.ts, src/invoker.ts, test/invoker.ts
- paths with favicon.ico and robots.txt will send 404 and no longer invoke function.
=> Adjust path handling

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.5.0

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.5.1

package.json
=> fix: add functions-framework-nodejs executable

.github/renovate.json, renovate.json
Also move renovate.json into .github directory.
=> chore(deps): automerge all but major updates

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.7.0

tslint.json
=> chore: remove tslint.json

CHANGELOG.md, package.json
=> Release @google-cloud/functions-framework v1.7.1

docs/README.md, docs/typescript.md
Also lints README by indenting some codeblocks in enumerated lists.
=> docs: add ts example

.github/renovate.json
Reduce Renovate to every 13 weeks instead of 1 week.
=> Quarterly renovate.json

.github/workflows/conformance.yml, .github/workflows/lint.yml, .github/workflows/unit.yml, package.json
- Standardizes unit/lint/conformance workflow filenames and workflow names.
- Splits workflows (unit/lint/conformance)
- Minor formatting
Supports https://github.com/GoogleCloudPlatform/functions-framework/pull/37
=> ci: split GH actions

package.json, src/functions.ts
- Re-adds the TS interfaces in package types.
Fixes: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/216
=> fix: re-add interfaces

src/index.ts
=> fix: Log function signature type

package-lock.json, package.json
Updates various npm dependencies using `npm update`.
=> chore: update dependencies [2021/3]

CONTRIBUTING.md, package.json
- Adds some useful scripts to this package: testing an individual test, tsc watching
=> chore: add useful npm scripts

src/cloudevents.ts, src/functions.ts
- Updates the function interfaces for the Node FF
- Adds a `LegacyEvent` interface
- Updates `CloudEvent` interface to CE 1.0 (must have been <1.0 with `schemaurl`)
=> feat: updates event and cloudevent interfaces

.github/workflows/conformance.yml, test/conformance/function.js
This allows us to use the new `workingDirectory` option to simplify things.
=> Udpate functions-framework-conformance action

CHANGELOG.md, package.json
update changelog and package.json version
=> Release @google-cloud/functions-framework v1.8.0

docs/README.md, docs/esm.md
- Add docs for using ESM
- Removes duplicate doc for debugging functions
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/302
=> docs: add docs for esm support

CONTRIBUTING.md
Adds a little documentation on how to develop this module locally.
Fixes https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/265.
=> docs: add docs for local admin dev

README.md
Also use source deploy instead of Dockerfile
=> docs: Cloud Run on GKE -> Cloud Run for Anthos

.github/workflows/unit.yml
- Unit test Node 16
- Use simple syntax like the docs: https://github.com/actions/setup-node
=> ci: unit test node 16

docs/generated/api.json, docs/generated/api.md, package-lock.json, package.json, src/cloud_event_types/cloud_events_context.ts, src/cloud_events.ts, src/function_wrappers.ts, src/functions.ts, test/function_wrappers.ts, test/integration/cloud_event.ts
Reverts GoogleCloudPlatform/functions-framework-nodejs#391.
@matthewrobertson will do a review of this PR a bit more and we can get this in:
- https://github.com/cloudevents/sdk-javascript/pull/449
=> Revert "refactor: use cesdk"

package-lock.json
Updates npm lockfile to v2.
See bug: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/423
=> chore: update lockfile to v2

package-lock.json, package.json
Updates cloudevents package to fix `ambient const enums` error.
Fixes #425
Lockfile update should be fixed with: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/426
=> chore: update cloudevents package

README.md, docs/cloudevents.md
- Remove step to add FF to deps, since we already install the FF above.
- Other minor docs cleanup
=> docs: simplify and clean cloudevent docs

.github/workflows/conformance.yml, test/conformance/function.js
Also, refactor conformance test Action to call the client directory,
similar to how one would run it locally.
=> chore: enable concurrency conformance test

docs/typescript.md
Fix function framework import for typescript cloud event function
=> docs: Update typescript.md

package-lock.json, package.json, src/types.ts, test/function_wrappers.ts
Update to latest version of gts
=> chore: update dependency gts to v5.0.1

src/server.ts, test/integration/http.ts
Addresses https://github.com/GoogleCloudPlatform/functions-framework-nodejs/issues/516
=> fix: etag should not be set on any response

.github/workflows/unit.yml
There seems to be [a bug](https://github.com/actions/setup-node/issues/1017) in the setup-node github action. I am hoping this fixes it.
=> chore: fix github actions

src/logger.ts, src/server.ts
invoker.ErrorHandler already does the work with sepcific error handling.
=> fix: remove logger.errorHandler.

package-lock.json, package.json
Reverts GoogleCloudPlatform/functions-framework-nodejs#687
breaks unit tests
=> Revert "chore(deps): update dependency body-parser to v2"
